In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
from matplotlib import pyplot as plt 
import missingno as msno
from datetime import date 
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import LocalOutlierFactor
from sklearn.preprocessing import MinMaxScaler, LabelEncoder, StandardScaler, RobustScaler

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.float_format", lambda x: "%.3f" % x)
pd.set_option("display.width", 500)

C:\Users\irem_\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
data =pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [3]:
data.head()

   customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService     MultipleLines InternetService OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges Churn
0  7590-VHVEG  Female              0     Yes         No       1           No  No phone service             DSL             No          Yes               No          No          No              No  Month-to-month              Yes           Electronic check          29.850        29.85    No
1  5575-GNVDE    Male              0      No         No      34          Yes                No             DSL            Yes           No              Yes          No          No              No        One year               No               Mailed check          56.950       1889.5    No
2  3668-QPYBK    Male              0      No         No       2          Yes                No             DSL            Yes          Yes               No          No          No              No  Month-to-month              Yes               Mailed check          53.850       108.15   Yes
3  7795-CFOCW    Male              0      No         No      45           No  No phone service             DSL            Yes           No              Yes         Yes          No              No        One year               No  Bank transfer (automatic)          42.300      1840.75    No
4  9237-HQITU  Female              0      No         No       2          Yes                No     Fiber optic             No           No               No          No          No              No  Month-to-month              Yes           Electronic check          70.700       151.65   Yes

In [4]:
#bütün değişkenlerin ismin aynı boyuta getirelim 
data.columns =[col.upper()for col in data.columns]

In [5]:
data.head(20)

    CUSTOMERID  GENDER  SENIORCITIZEN PARTNER DEPENDENTS  TENURE PHONESERVICE     MULTIPLELINES INTERNETSERVICE       ONLINESECURITY         ONLINEBACKUP     DEVICEPROTECTION          TECHSUPPORT          STREAMINGTV      STREAMINGMOVIES        CONTRACT PAPERLESSBILLING              PAYMENTMETHOD  MONTHLYCHARGES TOTALCHARGES CHURN
0   7590-VHVEG  Female              0     Yes         No       1           No  No phone service             DSL                   No                  Yes                   No                   No                   No                   No  Month-to-month              Yes           Electronic check          29.850        29.85    No
1   5575-GNVDE    Male              0      No         No      34          Yes                No             DSL                  Yes                   No                  Yes                   No                   No                   No        One year               No               Mailed check          56.950       1889.5    No
2   3668-QPYBK    Male              0      No         No       2          Yes                No             DSL                  Yes                  Yes                   No                   No                   No                   No  Month-to-month              Yes               Mailed check          53.850       108.15   Yes
3   7795-CFOCW    Male              0      No         No      45           No  No phone service             DSL                  Yes                   No                  Yes                  Yes                   No                   No        One year               No  Bank transfer (automatic)          42.300      1840.75    No
4   9237-HQITU  Female              0      No         No       2          Yes                No     Fiber optic                   No                   No                   No                   No                   No                   No  Month-to-month              Yes           Electronic check          70.700       151.65   Yes
5   9305-CDSKC  Female              0      No         No       8          Yes               Yes     Fiber optic                   No                   No                  Yes                   No                  Yes                  Yes  Month-to-month              Yes           Electronic check          99.650        820.5   Yes
6   1452-KIOVK    Male              0      No        Yes      22          Yes               Yes     Fiber optic                   No                  Yes                   No                   No                  Yes                   No  Month-to-month              Yes    Credit card (automatic)          89.100       1949.4    No
7   6713-OKOMC  Female              0      No         No      10           No  No phone service             DSL                  Yes                   No                   No                   No                   No                   No  Month-to-month               No               Mailed check          29.750        301.9    No
8   7892-POOKP  Female              0     Yes         No      28          Yes               Yes     Fiber optic                   No                   No                  Yes                  Yes                  Yes                  Yes  Month-to-month              Yes           Electronic check         104.800      3046.05   Yes
9   6388-TABGU    Male              0      No        Yes      62          Yes                No             DSL                  Yes                  Yes                   No                   No                   No                   No        One year               No  Bank transfer (automatic)          56.150      3487.95    No
10  9763-GRSKD    Male              0     Yes        Yes      13          Yes                No             DSL                  Yes                   No                   No                   No                   No                   No  Month-to-month              Yes               Mailed check          49.950       587.45    No
11  7469-LKBCI    Male              0      No         No      16          Yes                No              No  No internet service  No internet service  No internet service  No internet service  No internet service  No internet service        Two year               No    Credit card (automatic)          18.950        326.8    No
12  8091-TTVAX    Male              0     Yes         No      58          Yes               Yes     Fiber optic                   No                   No                  Yes                   No                  Yes                  Yes        One year               No    Credit card (automatic)         100.350       5681.1    No
13  0280-XJGEX    Male              0      No         No      49          Yes               Yes     Fiber optic                   No                  Yes                  Yes                   No                  Yes                  Yes  Month-to-month              Yes  Bank transfer (automatic)         103.700       5036.3   Yes
14  5129-JLPIS    Male              0      No         No      25          Yes                No     Fiber optic                  Yes                   No                  Yes                  Yes                  Yes                  Yes  Month-to-month              Yes           Electronic check         105.500      2686.05    No
15  3655-SNQYZ  Female              0     Yes        Yes      69          Yes               Yes     Fiber optic                  Yes                  Yes                  Yes                  Yes                  Yes                  Yes        Two year               No    Credit card (automatic)         113.250      7895.15    No
16  8191-XWSZG  Female              0      No         No      52          Yes                No              No  No internet service  No internet service  No internet service  No internet service  No internet service  No internet service        One year               No               Mailed check          20.650      1022.95    No
17  9959-WOFKT    Male              0      No        Yes      71          Yes               Yes     Fiber optic                  Yes                   No                  Yes                   No                  Yes                  Yes        Two year               No  Bank transfer (automatic)         106.700      7382.25    No
18  4190-MFLUW  Female              0     Yes        Yes      10          Yes                No             DSL                   No                   No                  Yes                  Yes                   No                   No  Month-to-month               No    Credit card (automatic)          55.200       528.35   Yes
19  4183-MYFRB  Female              0      No         No      21          Yes                No     Fiber optic                   No                  Yes                  Yes                   No                   No                  Yes  Month-to-month              Yes           Electronic check          90.050       1862.9    No

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CUSTOMERID        7043 non-null   object
 1   GENDER            7043 non-null   object
 2   SENIORCITIZEN     7043 non-null   int64
 3   PARTNER           7043 non-null   object
 4   DEPENDENTS        7043 non-null   object
 5   TENURE            7043 non-null   int64
 6   PHONESERVICE      7043 non-null   object
 7   MULTIPLELINES     7043 non-null   object
 8   INTERNETSERVICE   7043 non-null   object
 9   ONLINESECURITY    7043 non-null   object
 10  ONLINEBACKUP      7043 non-null   object
 11  DEVICEPROTECTION  7043 non-null   object
 12  TECHSUPPORT       7043 non-null   object
 13  STREAMINGTV       7043 non-null   object
 14  STREAMINGMOVIES   7043 non-null   object
 15  CONTRACT          7043 non-null   object
 16  PAPERLESSBILLING  7043 non-null   object
 17  PAYMENTMETHOD     7043 non-null   object
 18  MONTHLYCHARGES    7043 non-null   float64
 19  TOTALCHARGES      7043 non-null   object
 20  CHURN             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [7]:
data['INTERNETSERVICE'].value_counts()

INTERNETSERVICE
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

In [8]:
data.TENURE.min()

0

In [9]:
data.TENURE.max()

72

In [10]:
data.shape

(7043, 21)

In [11]:
data.describe()

       SENIORCITIZEN   TENURE  MONTHLYCHARGES
count       7043.000 7043.000        7043.000
mean           0.162   32.371          64.762
std            0.369   24.559          30.090
min            0.000    0.000          18.250
25%            0.000    9.000          35.500
50%            0.000   29.000          70.350
75%            0.000   55.000          89.850
max            1.000   72.000         118.750

In [12]:
#1)değişken mühendisliği
# Name count
data["NEW_CUSTOMERID_COUNT"] = data["CUSTOMERID"].str.len()
# name word count
data["NEW_NAME_INTERNETSERVICE_COUNT"] = data["INTERNETSERVICE"].apply(lambda x: len(str(x).split(" ")))
# name dr
data["INTERNETSERVICE_DSL"] = data["INTERNETSERVICE"].apply(lambda x: len([x for x in x.split() if x.startswith("DSL")]))
# name word count
data["NEW_NAME_PAYMENTMETHOD_COUNT"] = data["PAYMENTMETHOD"].apply(lambda x: len(str(x).split(" ")))
# age level
data.loc[(data['TENURE'] <16), 'NEW_TENURE_CAT'] = 'young_customer'
data.loc[(data['TENURE'] >= 17) & (data['TENURE'] < 32), 'NEW_TENURE_CAT'] = 'mature_customer'
data.loc[(data['TENURE'] >= 33), 'NEW_TENURE_CAT'] = 'senior_customer'
# sex x age
data.loc[(data['GENDER'] == 'Male') & (data['TENURE'] <= 21), 'NEW_GENDER_CAT'] = 'youngmalecustomer'
data.loc[(data['GENDER'] == 'Male') & (data['TENURE'] > 21) & (data['TENURE'] < 50), 'NEW_GENDER_CAT'] = 'maturemalecustomer'
data.loc[(data['GENDER'] == 'Male') & (data['TENURE'] >= 50), 'NEW_GENDER_CAT'] = 'seniormalecustomer'
data.loc[(data['GENDER'] == 'Female') & (data['TENURE'] <= 21), 'NEW_GENDER_CAT'] = 'youngfemalecustomer'
data.loc[(data['GENDER'] == 'Female') & (data['TENURE'] > 21) & (data['TENURE'] < 50), 'NEW_GENDER_CAT'] = 'maturefemalecustomer'
data.loc[(data['GENDER'] == 'Female') & (data['TENURE'] >= 50), 'NEW_GENDER_CAT'] = 'seniorfemalecustomer'

In [13]:
data.head(20)

    CUSTOMERID  GENDER  SENIORCITIZEN PARTNER DEPENDENTS  TENURE PHONESERVICE     MULTIPLELINES INTERNETSERVICE       ONLINESECURITY         ONLINEBACKUP     DEVICEPROTECTION          TECHSUPPORT          STREAMINGTV      STREAMINGMOVIES        CONTRACT PAPERLESSBILLING              PAYMENTMETHOD  MONTHLYCHARGES TOTALCHARGES CHURN  NEW_CUSTOMERID_COUNT  NEW_NAME_INTERNETSERVICE_COUNT  INTERNETSERVICE_DSL  NEW_NAME_PAYMENTMETHOD_COUNT   NEW_TENURE_CAT        NEW_GENDER_CAT
0   7590-VHVEG  Female              0     Yes         No       1           No  No phone service             DSL                   No                  Yes                   No                   No                   No                   No  Month-to-month              Yes           Electronic check          29.850        29.85    No                    10                               1                    1                             2   young_customer   youngfemalecustomer
1   5575-GNVDE    Male              0      No         No      34          Yes                No             DSL                  Yes                   No                  Yes                   No                   No                   No        One year               No               Mailed check          56.950       1889.5    No                    10                               1                    1                             2  senior_customer    maturemalecustomer
2   3668-QPYBK    Male              0      No         No       2          Yes                No             DSL                  Yes                  Yes                   No                   No                   No                   No  Month-to-month              Yes               Mailed check          53.850       108.15   Yes                    10                               1                    1                             2   young_customer     youngmalecustomer
3   7795-CFOCW    Male              0      No         No      45           No  No phone service             DSL                  Yes                   No                  Yes                  Yes                   No                   No        One year               No  Bank transfer (automatic)          42.300      1840.75    No                    10                               1                    1                             3  senior_customer    maturemalecustomer
4   9237-HQITU  Female              0      No         No       2          Yes                No     Fiber optic                   No                   No                   No                   No                   No                   No  Month-to-month              Yes           Electronic check          70.700       151.65   Yes                    10                               2                    0                             2   young_customer   youngfemalecustomer
5   9305-CDSKC  Female              0      No         No       8          Yes               Yes     Fiber optic                   No                   No                  Yes                   No                  Yes                  Yes  Month-to-month              Yes           Electronic check          99.650        820.5   Yes                    10                               2                    0                             2   young_customer   youngfemalecustomer
6   1452-KIOVK    Male              0      No        Yes      22          Yes               Yes     Fiber optic                   No                  Yes                   No                   No                  Yes                   No  Month-to-month              Yes    Credit card (automatic)          89.100       1949.4    No                    10                               2                    0                             3  mature_customer    maturemalecustomer
7   6713-OKOMC  Female              0      No         No      10           No  No phone service             DSL                  Yes                   No                   No                   No                   No                   No  Month-to-month               No               Mailed check          29.750        301.9    No                    10                               1                    1                             2   young_customer   youngfemalecustomer
8   7892-POOKP  Female              0     Yes         No      28          Yes               Yes     Fiber optic                   No                   No                  Yes                  Yes                  Yes                  Yes  Month-to-month              Yes           Electronic check         104.800      3046.05   Yes                    10                               2                    0                             2  mature_customer  maturefemalecustomer
9   6388-TABGU    Male              0      No        Yes      62          Yes                No             DSL                  Yes                  Yes                   No                   No                   No                   No        One year               No  Bank transfer (automatic)          56.150      3487.95    No                    10                               1                    1                             3  senior_customer    seniormalecustomer
10  9763-GRSKD    Male              0     Yes        Yes      13          Yes                No             DSL                  Yes                   No                   No                   No                   No                   No  Month-to-month              Yes               Mailed check          49.950       587.45    No                    10                               1                    1                             2   young_customer     youngmalecustomer
11  7469-LKBCI    Male              0      No         No      16          Yes                No              No  No internet service  No internet service  No internet service  No internet service  No internet service  No internet service        Two year               No    Credit card (automatic)          18.950        326.8    No                    10                               1                    0                             3              NaN     youngmalecustomer
12  8091-TTVAX    Male              0     Yes         No      58          Yes               Yes     Fiber optic                   No                   No                  Yes                   No                  Yes                  Yes        One year               No    Credit card (automatic)         100.350       5681.1    No                    10                               2                    0                             3  senior_customer    seniormalecustomer
13  0280-XJGEX    Male              0      No         No      49          Yes               Yes     Fiber optic                   No                  Yes                  Yes                   No                  Yes                  Yes  Month-to-month              Yes  Bank transfer (automatic)         103.700       5036.3   Yes                    10                               2                    0                             3  senior_customer    maturemalecustomer
14  5129-JLPIS    Male              0      No         No      25          Yes                No     Fiber optic                  Yes                   No                  Yes                  Yes                  Yes                  Yes  Month-to-month              Yes           Electronic check         105.500      2686.05    No                    10                               2                    0                             2  mature_customer    maturemalecustomer
15  3655-SNQYZ  Female              0     Yes        Yes      69          Yes               Yes     Fiber optic                  Yes                  Yes                  Yes                  Yes                  Yes                  Yes        Two year               No    Credit card (automatic)         113.250      7895.15    No                    10                               2                    0                             3  senior_customer  seniorfemalecustomer
16  8191-XWSZG  Female              0      No         No      52          Yes                No              No  No internet service  No internet service  No internet service  No internet service  No internet service  No internet service        One year               No               Mailed check          20.650      1022.95    No                    10                               1                    0                             2  senior_customer  seniorfemalecustomer
17  9959-WOFKT    Male              0      No        Yes      71          Yes               Yes     Fiber optic                  Yes                   No                  Yes                   No                  Yes                  Yes        Two year               No  Bank transfer (automatic)         106.700      7382.25    No                    10                               2                    0                             3  senior_customer    seniormalecustomer
18  4190-MFLUW  Female              0     Yes        Yes      10          Yes                No             DSL                   No                   No                  Yes                  Yes                   No                   No  Month-to-month               No    Credit card (automatic)          55.200       528.35   Yes                    10                               1                    1                             3   young_customer   youngfemalecustomer
19  4183-MYFRB  Female              0      No         No      21          Yes                No     Fiber optic                   No                  Yes                  Yes                   No                   No                  Yes  Month-to-month              Yes           Electronic check          90.050       1862.9    No                    10                               2                    0                             2  mature_customer   youngfemalecustomer

In [14]:
def grab_nol_names(dataframe,ct_th=10,car_th=20):
    cat_cols=[col for col in data.columns if str(data[col].dtypes)in ["object","bool","category"]]
    num_but_cat=[col for col in data.columns if data[col].dtypes in ["int64","float64"] and data[col].nunique()<10]
    cat_but_car=[col for col in data.columns if str(data[col].dtypes)in ["object","bool","category"] and data[col].nunique()>20]
    cat_cols=cat_cols+num_but_cat#temiz halde kategorik değişkenleri ayırdık 
    cat_cols =[col for col in cat_cols if col not in cat_but_car] #asdres ve isim gibi olanları çıkarıp ayırdık 
    num_col=[col for col in data.columns if data[col].dtypes in ["int64","float64"] ]
    num_col=[col for col in num_col if col not in cat_cols]
    print(f"obsevation:{dataframe.shape[0]}")
    print(f"Varibles:{dataframe.shape[1]}")
    print(f"cat_cols:{len(cat_cols)}")
    print(f"num_cols:{len(num_col)}")
    print(f"cat_but_car:{len(cat_but_car)}")
    print(f"num_but_cat:{len(num_but_cat)}")
    return cat_cols ,num_col,cat_but_car

In [15]:
cat_cols, num_cols, cat_but_car = grab_nol_names(data)

obsevation:7043
Varibles:27
cat_cols:23
num_cols:2
cat_but_car:2
num_but_cat:5

In [16]:
num_cols = [col for col in num_cols if "CUSTOMERID" not in col]

In [20]:
#2)Aykırı değerler 
for col in num_cols:
    print(col, check_outlier(data, col))
# false olduğu için aykırı değerim yoktur

TENURE False
MONTHLYCHARGES False

In [21]:
def check_outlier(dataframe,col_name):
    low_limit,up_limit=outlier_treshold(dataframe,col_name)
    if dataframe[(dataframe[col_name]< low_limit)|(dataframe[col_name]> up_limit)].any(axis=None):
        return True
    else:
        return False

In [22]:
def outlier_treshold(dataframe,col_name,q1=0.25,q3=0.75):
    quartile1=dataframe[col_name].quantile(q1)
    quartile3=dataframe[col_name].quantile(q3)
    interquartile=quartile3-quartile1
    up_limit=quartile3+1.5*interquartile
    low_limit=quartile1-1.5*interquartile
    return low_limit,up_limit

In [23]:
#3( eksik değerler missing values )

data.isnull().sum().sum()

149

In [24]:
data.isnull().sum()

CUSTOMERID                          0
GENDER                              0
SENIORCITIZEN                       0
PARTNER                             0
DEPENDENTS                          0
TENURE                              0
PHONESERVICE                        0
MULTIPLELINES                       0
INTERNETSERVICE                     0
ONLINESECURITY                      0
ONLINEBACKUP                        0
DEVICEPROTECTION                    0
TECHSUPPORT                         0
STREAMINGTV                         0
STREAMINGMOVIES                     0
CONTRACT                            0
PAPERLESSBILLING                    0
PAYMENTMETHOD                       0
MONTHLYCHARGES                      0
TOTALCHARGES                        0
CHURN                               0
NEW_CUSTOMERID_COUNT                0
NEW_NAME_INTERNETSERVICE_COUNT      0
INTERNETSERVICE_DSL                 0
NEW_NAME_PAYMENTMETHOD_COUNT        0
NEW_TENURE_CAT                    149
NEW_GENDER_CAT                      0
dtype: int64

In [ ]:
data.isnull().sum()

In [27]:
mode_value = data['NEW_TENURE_CAT'].mode()[0]
data['NEW_TENURE_CAT'].fillna(mode_value, inplace=True)

C:\Users\irem_\AppData\Local\Temp\ipykernel_19204\1773719247.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['NEW_TENURE_CAT'].fillna(mode_value, inplace=True)

In [28]:
data.isnull().sum()

CUSTOMERID                        0
GENDER                            0
SENIORCITIZEN                     0
PARTNER                           0
DEPENDENTS                        0
TENURE                            0
PHONESERVICE                      0
MULTIPLELINES                     0
INTERNETSERVICE                   0
ONLINESECURITY                    0
ONLINEBACKUP                      0
DEVICEPROTECTION                  0
TECHSUPPORT                       0
STREAMINGTV                       0
STREAMINGMOVIES                   0
CONTRACT                          0
PAPERLESSBILLING                  0
PAYMENTMETHOD                     0
MONTHLYCHARGES                    0
TOTALCHARGES                      0
CHURN                             0
NEW_CUSTOMERID_COUNT              0
NEW_NAME_INTERNETSERVICE_COUNT    0
INTERNETSERVICE_DSL               0
NEW_NAME_PAYMENTMETHOD_COUNT      0
NEW_TENURE_CAT                    0
NEW_GENDER_CAT                    0
dtype: int64

In [29]:
#4)kategorik olanları integer 0,1 dönüştürüp label encoding yapıyoruz

binary_cols = [col for col in data.columns if data[col].dtype not in [int, float]
               and data[col].nunique() == 2]

In [30]:
def label_encoder(dataframe, binary_col):
    labelencoder = LabelEncoder()
    dataframe[binary_col] = labelencoder.fit_transform(dataframe[binary_col])
    return dataframe
#binarycol yani iki sınıflı değikenler için

In [31]:
binary_cols

['GENDER',
 'SENIORCITIZEN',
 'PARTNER',
 'DEPENDENTS',
 'PHONESERVICE',
 'PAPERLESSBILLING',
 'CHURN',
 'NEW_NAME_INTERNETSERVICE_COUNT',
 'INTERNETSERVICE_DSL',
 'NEW_NAME_PAYMENTMETHOD_COUNT']

In [32]:
for col in binary_cols:
    data = label_encoder(data, col)

In [33]:
#5)Rare Encoding

#data = rare_encoder(data, 0.01)

In [35]:
"""
def rare_encoder(dataframe, rare_perc):
    temp_df = dataframe.copy()

    rare_columns = [col for col in temp_df.columns if temp_df[col].dtypes == 'O'
                    and (temp_df[col].value_counts() / len(temp_df) < rare_perc).any(axis=None)]

    for var in rare_columns:
        tmp = temp_df[var].value_counts() / len(temp_df)
        rare_labels = tmp[tmp < rare_perc].index
        temp_df[var] = np.where(temp_df[var].isin(rare_labels), 'Rare', temp_df[var])

    return temp_df
"""

"\ndef rare_encoder(dataframe, rare_perc):\n    temp_df = dataframe.copy()\n\n    rare_columns = [col for col in temp_df.columns if temp_df[col].dtypes == 'O'\n                    and (temp_df[col].value_counts() / len(temp_df) < rare_perc).any(axis=None)]\n\n    for var in rare_columns:\n        tmp = temp_df[var].value_counts() / len(temp_df)\n        rare_labels = tmp[tmp < rare_perc].index\n        temp_df[var] = np.where(temp_df[var].isin(rare_labels), 'Rare', temp_df[var])\n\n    return temp_df\n"

In [36]:
def rare_analyser(dataframe, target, cat_cols):
    for col in cat_cols:
        print(col, ":", len(dataframe[col].value_counts()))
        print(pd.DataFrame({"COUNT": dataframe[col].value_counts(),
                            "RATIO": dataframe[col].value_counts() / len(dataframe),
                            "TARGET_MEAN": dataframe.groupby(col)[target].mean()}), end="\n\n\n")

In [37]:
rare_analyser(data, "CHURN", cat_cols)

GENDER : 2
        COUNT  RATIO  TARGET_MEAN
GENDER
0        3488  0.495        0.269
1        3555  0.505        0.262


PARTNER : 2
         COUNT  RATIO  TARGET_MEAN
PARTNER
0         3641  0.517        0.330
1         3402  0.483        0.197


DEPENDENTS : 2
            COUNT  RATIO  TARGET_MEAN
DEPENDENTS
0            4933  0.700        0.313
1            2110  0.300        0.155


PHONESERVICE : 2
              COUNT  RATIO  TARGET_MEAN
PHONESERVICE
0               682  0.097        0.249
1              6361  0.903        0.267


MULTIPLELINES : 3
                  COUNT  RATIO  TARGET_MEAN
MULTIPLELINES
No                 3390  0.481        0.250
No phone service    682  0.097        0.249
Yes                2971  0.422        0.286


INTERNETSERVICE : 3
                 COUNT  RATIO  TARGET_MEAN
INTERNETSERVICE
DSL               2421  0.344        0.190
Fiber optic       3096  0.440        0.419
No                1526  0.217        0.074


ONLINESECURITY : 3
                     COUNT  RATIO  TARGET_MEAN
ONLINESECURITY
No                    3498  0.497        0.418
No internet service   1526  0.217        0.074
Yes                   2019  0.287        0.146


ONLINEBACKUP : 3
                     COUNT  RATIO  TARGET_MEAN
ONLINEBACKUP
No                    3088  0.438        0.399
No internet service   1526  0.217        0.074
Yes                   2429  0.345        0.215


DEVICEPROTECTION : 3
                     COUNT  RATIO  TARGET_MEAN
DEVICEPROTECTION
No                    3095  0.439        0.391
No internet service   1526  0.217        0.074
Yes                   2422  0.344        0.225


TECHSUPPORT : 3
                     COUNT  RATIO  TARGET_MEAN
TECHSUPPORT
No                    3473  0.493        0.416
No internet service   1526  0.217        0.074
Yes                   2044  0.290        0.152


STREAMINGTV : 3
                     COUNT  RATIO  TARGET_MEAN
STREAMINGTV
No                    2810  0.399        0.335
No internet service   1526  0.217        0.074
Yes                   2707  0.384        0.301


STREAMINGMOVIES : 3
                     COUNT  RATIO  TARGET_MEAN
STREAMINGMOVIES
No                    2785  0.395        0.337
No internet service   1526  0.217        0.074
Yes                   2732  0.388        0.299


CONTRACT : 3
                COUNT  RATIO  TARGET_MEAN
CONTRACT
Month-to-month   3875  0.550        0.427
One year         1473  0.209        0.113
Two year         1695  0.241        0.028


PAPERLESSBILLING : 2
                  COUNT  RATIO  TARGET_MEAN
PAPERLESSBILLING
0                  2872  0.408        0.163
1                  4171  0.592        0.336


PAYMENTMETHOD : 4
                           COUNT  RATIO  TARGET_MEAN
PAYMENTMETHOD
Bank transfer (automatic)   1544  0.219        0.167
Credit card (automatic)     1522  0.216        0.152
Electronic check            2365  0.336        0.453
Mailed check                1612  0.229        0.191


CHURN : 2
       COUNT  RATIO  TARGET_MEAN
CHURN
0       5174  0.735        0.000
1       1869  0.265        1.000


NEW_TENURE_CAT : 3
                 COUNT  RATIO  TARGET_MEAN
NEW_TENURE_CAT
mature_customer   1156  0.164        0.240
senior_customer   3417  0.485        0.133
young_customer    2470  0.351        0.460


NEW_GENDER_CAT : 6
                      COUNT  RATIO  TARGET_MEAN
NEW_GENDER_CAT
maturefemalecustomer    966  0.137        0.213
maturemalecustomer      963  0.137        0.205
seniorfemalecustomer   1056  0.150        0.076
seniormalecustomer     1117  0.159        0.106
youngfemalecustomer    1466  0.208        0.445
youngmalecustomer      1475  0.209        0.417


SENIORCITIZEN : 2
               COUNT  RATIO  TARGET_MEAN
SENIORCITIZEN
0               5901  0.838        0.236
1               1142  0.162        0.417


NEW_CUSTOMERID_COUNT : 1
                      COUNT  RATIO  TARGET_MEAN
NEW_CUSTOMERID_COUNT
10                     7043  1.000        0.265


NEW_NAME_INTERNETSERVICE_COUNT : 2
                                COUNT  RATIO  TARGET_MEAN
NEW_NAME_INTERNETSERVICE_COUNT
0                                3947  0.560        0.145
1                                3096  0.440        0.419


INTERNETSERVICE_DSL : 2
                     COUNT  RATIO  TARGET_MEAN
INTERNETSERVICE_DSL
0                     4622  0.656        0.305
1                     2421  0.344        0.190


NEW_NAME_PAYMENTMETHOD_COUNT : 2
                              COUNT  RATIO  TARGET_MEAN
NEW_NAME_PAYMENTMETHOD_COUNT
0                              3977  0.565        0.347
1                              3066  0.435        0.160

In [38]:
data.head()

   CUSTOMERID  GENDER  SENIORCITIZEN  PARTNER  DEPENDENTS  TENURE  PHONESERVICE     MULTIPLELINES INTERNETSERVICE ONLINESECURITY ONLINEBACKUP DEVICEPROTECTION TECHSUPPORT STREAMINGTV STREAMINGMOVIES        CONTRACT  PAPERLESSBILLING              PAYMENTMETHOD  MONTHLYCHARGES TOTALCHARGES  CHURN  NEW_CUSTOMERID_COUNT  NEW_NAME_INTERNETSERVICE_COUNT  INTERNETSERVICE_DSL  NEW_NAME_PAYMENTMETHOD_COUNT   NEW_TENURE_CAT       NEW_GENDER_CAT
0  7590-VHVEG       0              0        1           0       1             0  No phone service             DSL             No          Yes               No          No          No              No  Month-to-month                 1           Electronic check          29.850        29.85      0                    10                               0                    1                             0   young_customer  youngfemalecustomer
1  5575-GNVDE       1              0        0           0      34             1                No             DSL            Yes           No              Yes          No          No              No        One year                 0               Mailed check          56.950       1889.5      0                    10                               0                    1                             0  senior_customer   maturemalecustomer
2  3668-QPYBK       1              0        0           0       2             1                No             DSL            Yes          Yes               No          No          No              No  Month-to-month                 1               Mailed check          53.850       108.15      1                    10                               0                    1                             0   young_customer    youngmalecustomer
3  7795-CFOCW       1              0        0           0      45             0  No phone service             DSL            Yes           No              Yes         Yes          No              No        One year                 0  Bank transfer (automatic)          42.300      1840.75      0                    10                               0                    1                             1  senior_customer   maturemalecustomer
4  9237-HQITU       0              0        0           0       2             1                No     Fiber optic             No           No               No          No          No              No  Month-to-month                 1           Electronic check          70.700       151.65      1                    10                               1                    0                             0   young_customer  youngfemalecustomer

In [39]:
#5)one hot encoder 
ohe_cols = [col for col in data.columns if 10 >= data[col].nunique() > 2]

In [40]:
def one_hot_encoder(dataframe, categorical_cols, drop_first=True):
    dataframe = pd.get_dummies(dataframe, columns=categorical_cols, drop_first=drop_first)
    return dataframe

In [41]:
data = one_hot_encoder(data, ohe_cols)

In [45]:
data.head()

,CUSTOMERID,GENDER,SENIORCITIZEN,PARTNER,DEPENDENTS,TENURE,PHONESERVICE,PAPERLESSBILLING,MONTHLYCHARGES,TOTALCHARGES,CHURN,NEW_CUSTOMERID_COUNT,NEW_NAME_INTERNETSERVICE_COUNT,INTERNETSERVICE_DSL,NEW_NAME_PAYMENTMETHOD_COUNT,MULTIPLELINES_No phone service,MULTIPLELINES_Yes,INTERNETSERVICE_Fiber optic,INTERNETSERVICE_No,ONLINESECURITY_No internet service,ONLINESECURITY_Yes,ONLINEBACKUP_No internet service,ONLINEBACKUP_Yes,DEVICEPROTECTION_No internet service,DEVICEPROTECTION_Yes,TECHSUPPORT_No internet service,TECHSUPPORT_Yes,STREAMINGTV_No internet service,STREAMINGTV_Yes,STREAMINGMOVIES_No internet service,STREAMINGMOVIES_Yes,CONTRACT_One year,CONTRACT_Two year,PAYMENTMETHOD_Credit card (automatic),PAYMENTMETHOD_Electronic check,PAYMENTMETHOD_Mailed check,NEW_TENURE_CAT_senior_customer,NEW_TENURE_CAT_young_customer,NEW_GENDER_CAT_maturemalecustomer,NEW_GENDER_CAT_seniorfemalecustomer,NEW_GENDER_CAT_seniormalecustomer,NEW_GENDER_CAT_youngfemalecustomer,NEW_GENDER_CAT_youngmalecustomer
0,7590-VHVEG,0,0,1,0,1,0,1,29.850,29.85,0,10,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0
1,5575-GNVDE,1,0,0,0,34,1,0,56.950,1889.5,0,10,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,1,0,1,0,0,0,0
2,3668-QPYBK,1,0,0,0,2,1,1,53.850,108.15,1,10,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1
3,7795-CFOCW,1,0,0,0,45,0,0,42.300,1840.75,0,10,0,1,1,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0
4,9237-HQITU,0,0,0,0,2,1,1,70.700,151.65,1,10,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0

In [43]:
useless_cols = [col for col in data.columns if data[col].nunique() == 2 and
                (data[col].value_counts() / len(data) < 0.01).any(axis=None)]

In [44]:
data = data.applymap(lambda x: 1 if x is True else (0 if x is False else x))

C:\Users\irem_\AppData\Local\Temp\ipykernel_19204\2823618222.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  data = data.applymap(lambda x: 1 if x is True else (0 if x is False else x))

# model

In [50]:
# 'TOTALCHARGES' sütunundaki boş stringleri (') NaN ile değiştir
data['TOTALCHARGES'].replace(' ', pd.NA, inplace=True)

# NaN değerleri sayısal veriye dönüştür ve doldur
data['TOTALCHARGES'] = pd.to_numeric(data['TOTALCHARGES'])
data['TOTALCHARGES'].fillna(data['TOTALCHARGES'].mean(), inplace=True)

# True/False değerlerini 0/1 olarak dönüştürme
data = data.applymap(lambda x: 1 if x is True else (0 if x is False else x))

# Bağımlı ve bağımsız değişkenleri ayırma
y = data["CHURN"]
X = data.drop(["CUSTOMERID", "CHURN"], axis=1)

# Veriyi eğitim ve test setlerine ayırma
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=21)

# Modeli oluşturma ve eğitme
rf_model = RandomForestClassifier(random_state=42).fit(X_train, y_train)

# Test verisi üzerinde tahmin yapma
y_pred = rf_model.predict(X_test)

# Modelin doğruluğunu hesaplama
accuracy = accuracy_score(y_test, y_pred)

print(f"Model accuracy: {accuracy}")

C:\Users\irem_\AppData\Local\Temp\ipykernel_19204\4257869154.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['TOTALCHARGES'].replace(' ', pd.NA, inplace=True)
C:\Users\irem_\AppData\Local\Temp\ipykernel_19204\4257869154.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['TOTALCHARGES'].fillna(data['TOTALCHARGES'].mean(), inplace=True)
C:\Users\irem_\AppData\Local\Temp\ipykernel_19204\4257869154.py:9: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  data = data.applymap(lambda x: 1 if x is True else (0 if x is False else x))

Model accuracy: 0.7936583057264552

#########finishingggg